
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Bayview','Candlestick Point SRA','Central Waterfront','Dogpatch',
'Hunters Point','India Basin','Little Hollywood','Portola','Potrero Hill','Silver Terrace','University Mound'); 
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Aquatic Park / Ft. Mason','Bret Harte','Chinatown','Downtown / Union Square','Fairmount','Financial District','Lower Nob Hill','Mint Hill','Nob Hill',
'North Beach','Northern Waterfront','Polk Gulch','Rincon Hill','Russian Hill','Telegraph Hill');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Bernal Heights','Crocker Amazon','Diamond Heights','Excelsior','Glen Park','Holly Park','Ingleside','McLaren Park','Miraloma Park','Mission Terrace','Outer Mission','Peralta Heights','Sherwood Forest','Sunnydale','Sunnyside',
'Visitacion Valley','Westwood Highlands','Westwood Park');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Dolores Heights','Eureka Valley','Mission','Mission Dolores','Noe Valley','Showplace Square');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Alamo Square','Cathedral Hill','Civic Center','Cow Hollow','Downtown/Civic Center','Hayes Valley','Japantown','Lower Haight','Lower Pacific Heights','Marina','Pacific Heights','Western Addition');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Anza Vista','Ashbury Heights','Buena Vista','Castro','Castro/Upper Market','Clarendon Heights','Cole Valley','Corona Heights','Duboce Triangle','Forest Knolls','Haight Ashbury','Laguna Honda','Midtown Terrace','Panhandle','Parnassus Heights','Twin Peaks','Upper Market','West of Twin Peaks');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Golden Gate Park','Inner Richmond','Lake Street','Laurel Heights / Jordan Park','Lincoln Park / Ft. Miley','Lone Mountain','Outer Richmond','Presidio Heights','Presidio Terrace','Seacliff','Sutro Heights');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Mission Bay','South Beach','South of Market','Treasure Island','Treasure Island/YBI','Yerba Buena Island');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood IN ('Balboa Terrace','Cayuga','Forest Hill','Golden Gate Heights','Ingleside Terraces','Inner Sunset','Lake Shore','Lakeshore','Merced Heights','Merced Manor','Monterey Heights','Mt. Davidson Manor','Ocean View','Oceanview','Outer Sunset','Parkmerced','Parkside','St. Francis Wood','Stonestown','West Portal');
SELECT count(*) FROM sf_311_probs WHERE Opened >= '01/01/2009' AND Category = 'Streetlights' AND Neighborhood = 'Tenderloin';